load("//scripts:scripts.bzl", "make_fuzz_scripts")

make_fuzz_scripts(
    name = "interleave",
)

make_fuzz_scripts(
    name = "checkpoints",
)

make_fuzz_scripts(
    name = "bounded_buffer",
)

# make_fuzz_scripts(
#     name = "elimination_backoff_stack",
# )
