cc_library(
    name = "unthread",
    srcs = [
        "unthread.c",
    ],
    hdrs = [
        "include/bits/pthreadtypes.h",
        "include/pthread.h",
    ],
    copts = [
        "-std=gnu11",
        "-I src/include",
    ],
    visibility = [
        "//visibility:public",
    ],
)
